---
- hosts: clusternodes
  tasks:
    - name: Check that the somefile.conf exists
      stat:
        path: /etc/docker
      register: stat_result

    - name: install docker
      script: install_docker.sh
      when: stat_result.stat.exists == False 
