---
- hosts: clusternodes
  tasks:
    - name: Check that the somefile.conf exists
      stat:
        path: ~/.ssh/authorized_keys
      register: stat_result

    - name: install docker
      script: install_docker.sh "PARAM001" "PARAM002"
      when: stat_result.stat.exists == False 
