---
- hosts: clusternodes
  remote_user: pi
  sudo: True

  tasks:
    - name: Check that the somefile.conf exists
      stat:
        path: /etc/docker
      register: stat_result

    - name: install docker
      script: install_docker.sh
      when: stat_result.stat.exists == False 

    - group: 
        name: docker
        state: present
      notify: 
      - restart docker

    - user: 
        name: pi
        groups: docker
        append: yes
      notify: 
      - restart docker

#    - debug:
#        msg: "FORCING restart of docker for testing"
#      changed_when: true
#      notify:
#      - restart docker

  handlers:
    - name: restart docker
      service: name=docker state=restarted
